steps:
  - name: gradle:5.6.3-jdk12
    entrypoint: gradle
    args: ["build"]
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: './cloudbuild.sh'
    env:
    -  'PROJECT_ID=$PROJECT_ID'
images: ['gcr.io/$PROJECT_ID/anz_test2']


