steps:
  - name: gradle:5.6.3-jdk12
    entrypoint: gradle
    args: ["build"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/anz_test2:$COMMIT_SHA','--build-arg=JAR_FILE=build/libs/simpleapplication.jar', '--build-arg=COMMIT_SHA=$COMMIT_SHA', '--build-arg=VERSION=5.0.0','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/anz_test2:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/anz_test2:latest']
images: ['gcr.io/$PROJECT_ID/anz_test2']
