FROM gradle:5.6.3-jdk12 as builder
WORKDIR /app
COPY build.gradle ./
COPY settings.gradle ./
COPY src ./src/
COPY config ./config/
RUN gradle clean build --no-daemon

FROM openjdk:12-jdk-alpine
ARG JAR_FILE=app/build/libs/simpleapplication.jar
ARG VERSION
ARG COMMIT_SHA
COPY --from=builder ${JAR_FILE} simpleapplication.jar
ENV VERSION=${VERSION} COMMIT_SHA=${COMMIT_SHA}

EXPOSE 8080
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/simpleapplication.jar"]
