apiVersion: apps/v1
kind: Deployment
metadata:
  name: anz-test2
  labels:
    app: anz-test2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anz-test2
  template:
    metadata:
      labels:
        app: anz-test2
    spec:
      containers:
        - name: anz-test2
          image: {IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 50
            timeoutSeconds: 2